### ISSUE TITLE
실기기에서 앱 실행 후 발생한 다크모드 ISSUE

### ISSUE THREAD

**Issue by Luna828** [underdog-FinalProject/carlog#39]
## 🚨ISSUE 발생🚨

- 실기기에서 앱을 실행한 뒤 생긴 ISSUE
    - MyCarPage에 백그라운드 색이 없음
    - MyHistoryPage에 백그라운드 색이 없음
    - MyPage에 맨 위에 있는 title 색이 배경 위에 올라오지 않음
    - MyPage에 있는 textfield의 text 색이 회색임 → 검은색으로 변경요청

## ✨방안 ✨
1. 다크모드를 지원하기
2. 모든 배경을 .white로 변경하기

@pinocchio22 , @luttoli , @user2rum , @gunnieee  님의 의견은 어떤가요? 방안 중에 택 1해서 comment에 알려주시면 감사하겠습니다!

**Comment by pinocchio22** [comment]
2. 모든 배경을 .white로 변경하기

**Comment by Luna828** [comment]
MVP 까지는 다크모드를 지원하지않기 때문에 배경색은 .white로 고정하는 것으로 결정하였습니다.
