### ISSUE TITLE
[기능 문제 발생] 로그아웃, 회원탈퇴 시 로그인 페이지 재구동 ❌ 이슈 발생

### ISSUE THREAD

**Issue by Luna828** [underdog-FinalProject/carlog#72]
### 현재 상황

1. 앱 설치 회원가입 -> 로그인 -> Main TabBar Page -> 로그아웃/회원탈퇴 문제없음
2. 로그아웃/회원탈퇴 이후 다시 로그인 textField 클릭 시, **앱 멈춤** 발생 (AppDelegate에서 ERROR 뜸)
3. 다시 앱 실행 (로그인이 되어져있는 상태) -> Main TabBar Page (fullScreen이 아닌 Modal default 형식으로 나옴) -> 로그아웃/회원탈퇴 dismiss 하면서 닫히거나 앱 멈춤 발생

이러한 순서대로 앱이 중단되는 현상이 발견됩니다 
먼저 ERROR를 찾는 분이 계시다면 해결방법을 Comment에 남겨주시기 바랍니다.

**Comment by luttoli** [comment]
### 🚨ISSUE 해결방안🚨
```swift
deinit {
        NotificationCenter.default.removeObserver(self)
    }
```

NotificationCenter를 키보드 활성화 시 사용하고 있었는데 해당 부분을 사용하면서 observer을 제거하지 않아서 발생하는 이슈로
removeObserver를 통하여 17.0에서 확인 시 정상적으로 로그아웃 후 노출되는 다음 페이지에서
textField 활성화를 확인함
